package splendor.entity.bot;

import java.util.*;
import splendor.rules.*;
import splendor.entity.*;

// Generated by GPT-5.4: helped to debug the EasyBot strategies

/**
 * A simple bot that uses basic heuristics: buy cheap preferred-color cards,
 * collect gems toward visible targets, and reserve when nothing else is useful.
 */
public class EasyBot extends Bot {

    /**
     * Constructs an EasyBot with the given name and turn order.
     *
     * @param name      the bot's display name
     * @param turnOrder the bot's position in the turn order
     */
    public EasyBot(String name, int turnOrder) {
        super(name, turnOrder);
    }

    /**
     * Chooses and executes a move for this bot's turn.
     *
     * @param gameState the current game state
     * @param gameRules the game rules for validation
     * @return a description of the move chosen
     */
    @Override
    public String chooseMove(GameState gameState, GameRules gameRules) {
        List<GemColor> preferredColors = getPreferredBonusColors(gameState);
        List<CardChoice> affordable = getAffordableChoices(gameState, gameRules);

        if (affordable.size() > 0) {
            List<CardChoice> preferredAffordable = new ArrayList<>();
            for (CardChoice choice: affordable) {
                if (preferredColors.contains(choice.getCard().getBonus())) {
                    preferredAffordable.add(choice);
                }
            }
            if (preferredAffordable.size() > 0) {
                affordable = preferredAffordable;
            }
            if (affordable.size() == 1) {
                return buyChoice(affordable.get(0), gameState, gameRules);
            }
            CardChoice chosen = getCheapestAffordableCard(affordable, gameRules);
            return buyChoice(chosen, gameState, gameRules);
        }

        String gemMove = chooseGemMove(gameState, gameRules, preferredColors);
        if (!gemMove.equals("")) {
            return gemMove;
        }

        if (gameRules.canReserveCard(this)) {
            CardChoice reserveChoice = getReserveChoice(gameState, gameRules, preferredColors);
            if (reserveChoice != null) {
                return reserveChoice(reserveChoice, gameState, gameRules);
            }
        }

        return getName() + " had no useful move.";
    }

    /**
     * Returns the bot's preferred bonus colors based on noble needs or visible cards.
     *
     * @param gameState the current game state
     * @return a list of preferred GemColors
     */
    public List<GemColor> getPreferredBonusColors(GameState gameState) {
        List<GemColor> colors = getNeededColorsForNoble(getClosestNoble(gameState));
        if (colors.size() > 0) {
            return colors;
        }

        List<GemColor> fallback = new ArrayList<>();
        List<CardChoice> visible = getVisibleChoices(gameState);
        for (CardChoice choice: visible) {
            addColor(fallback, choice.getCard().getBonus());
            if (fallback.size() == 3) {
                break;
            }
        }
        return fallback;
    }

    /**
     * Returns the cheapest affordable card from the given choices by discounted cost and waste.
     *
     * @param choices   the list of affordable card choices
     * @param gameRules the game rules for cost calculation
     * @return the cheapest CardChoice
     */
    public CardChoice getCheapestAffordableCard(List<CardChoice> choices, GameRules gameRules) {
        int bestCost = Integer.MAX_VALUE;
        int bestWaste = Integer.MAX_VALUE;
        List<CardChoice> bestChoices = new ArrayList<>();

        for (CardChoice choice: choices) {
            int cost = getDiscountedCostTotal(gameRules, choice.getCard());
            int waste = getWasteCount(gameRules, choice.getCard());
            if (cost < bestCost) {
                bestChoices.clear();
                bestChoices.add(choice);
                bestCost = cost;
                bestWaste = waste;
            } else if (cost == bestCost) {
                if (waste < bestWaste) {
                    bestChoices.clear();
                    bestChoices.add(choice);
                    bestWaste = waste;
                } else if (waste == bestWaste) {
                    bestChoices.add(choice);
                }
            }
        }

        return chooseRandomChoice(bestChoices);
    }

    /**
     * Chooses a visible card to reserve that matches preferred colors and is closest to affordable.
     *
     * @param gameState       the current game state
     * @param gameRules       the game rules for cost calculation
     * @param preferredColors the bot's preferred gem colors
     * @return the best CardChoice to reserve, or null if none
     */
    public CardChoice getReserveChoice(GameState gameState, GameRules gameRules, List<GemColor> preferredColors) {
        List<CardChoice> visible = getVisibleChoices(gameState);
        List<CardChoice> matching = new ArrayList<>();

        for (CardChoice choice: visible) {
            if (preferredColors.contains(choice.getCard().getBonus())) {
                matching.add(choice);
            }
        }
        if (matching.size() > 0) {
            visible = matching;
        }

        CardChoice chosen = null;
        int leastMissing = Integer.MAX_VALUE;
        for (CardChoice choice: visible) {
            int missing = getMissingGems(gameRules, choice.getCard());
            if (chosen == null || missing < leastMissing) {
                chosen = choice;
                leastMissing = missing;
            }
        }
        return chosen;
    }

    /**
     * Chooses a gem-taking move based on weighted color preferences.
     *
     * @param gameState       the current game state
     * @param gameRules       the game rules for validation
     * @param preferredColors the bot's preferred gem colors
     * @return a description of the gem move taken, or empty string if none possible
     */
    public String chooseGemMove(GameState gameState, GameRules gameRules, List<GemColor> preferredColors) {
        Map<GemColor, Integer> weights = new HashMap<>();
        List<CardChoice> visible = getVisibleChoices(gameState);
        List<CardChoice> targets = new ArrayList<>();

        for (CardChoice choice: visible) {
            if (preferredColors.contains(choice.getCard().getBonus())) {
                targets.add(choice);
            }
        }
        if (targets.size() == 0) {
            targets = visible;
        }

        for (CardChoice choice: targets) {
            List<GemColor> colors = getNeededColorsForCard(gameRules, choice.getCard());
            for (GemColor color: colors) {
                addWeight(weights, color, 2);
            }
            addWeight(weights, choice.getCard().getBonus(), 1);
        }

        List<GemColor> best = getBestColors(weights, gameState, 4);
        if (best.size() >= 3 && gameRules.canTakeThreeDifferentGems(gameState.getGemBank())) {
            Collections.shuffle(best, getRandom());
            List<GemColor> choice = new ArrayList<>();
            choice.add(best.get(0));
            choice.add(best.get(1));
            choice.add(best.get(2));
            if (GameActions.takeThreeDifferent(this, gameState, gameRules, choice)) {
                return getName() + " took " + formatColors(choice) + ".";
            }
        }

        GemColor doubleColor = getBestDoubleColor(weights, gameState, gameRules);
        if (doubleColor != null && getRandom().nextBoolean()) {
            if (GameActions.takeTwoSame(this, gameState, gameRules, doubleColor)) {
                return getName() + " took 2 " + doubleColor.name() + ".";
            }
        }

        String fallback = fallbackRandomGemMove(gameState, gameRules);
        if (fallback.endsWith("had no useful move.")) {
            return "";
        }
        return fallback;
    }
}
