package splendor.entity.bot;

import java.util.*;
import splendor.rules.*;
import splendor.entity.card.*;
import splendor.entity.player.*;
import splendor.entity.*;

// Generated by GPT-5.4: helped to debug the HardBot strategies

/**
 * An advanced bot that uses scoring heuristics including card points, noble synergy,
 * opponent denial, tier penalties, and strategic gem collection.
 */
public class HardBot extends Bot {

    /**
     * Constructs a HardBot with the given name and turn order.
     *
     * @param name      the bot's display name
     * @param turnOrder the bot's position in the turn order
     */
    public HardBot(String name, int turnOrder) {
        super(name, turnOrder);
    }

    /**
     * Chooses and executes a move for this bot's turn using advanced heuristics.
     *
     * @param gameState the current game state
     * @param gameRules the game rules for validation
     * @return a description of the move chosen
     */
    @Override
    public String chooseMove(GameState gameState, GameRules gameRules) {
        boolean nobleFocus = gameState.getPlayers().size() >= 3;
        List<CardChoice> affordable = getAffordableChoices(gameState, gameRules);
        if (affordable.size() > 0) {
            CardChoice choice = getBestChoice(affordable, gameState, gameRules, nobleFocus);
            return buyChoice(choice, gameState, gameRules);
        }

        String gemMove = chooseGemMove(gameState, gameRules, nobleFocus);
        if (!gemMove.equals("")) {
            return gemMove;
        }
        
        CardChoice reserveChoice = getReserveChoice(gameState, gameRules, nobleFocus);
        if (reserveChoice != null) {
            return reserveChoice(reserveChoice, gameState, gameRules);
        }

        if (gameRules.canReserveCard(this) && isEarlyGame(gameState)) {
            int level = getHiddenReserveLevel(gameState, nobleFocus);
            if (level > 0) {
                return reserveHidden(level, gameState, gameRules);
            }
        }

        return fallbackRandomGemMove(gameState, gameRules);
    }

    /**
     * Picks the best card choice from a list based on the scoring heuristic.
     *
     * @param choices    the list of card choices to evaluate
     * @param gameState  the current game state
     * @param gameRules  the game rules for scoring
     * @param nobleFocus whether to prioritize noble-related bonuses
     * @return the best CardChoice
     */
    public CardChoice getBestChoice(List<CardChoice> choices, GameState gameState, GameRules gameRules, boolean nobleFocus) {
        int bestScore = Integer.MIN_VALUE;
        List<CardChoice> bestChoices = new ArrayList<>();

        for (CardChoice choice: choices) {
            int score = getCardScore(choice, gameState, gameRules, nobleFocus);
            if (score > bestScore) {
                bestChoices.clear();
                bestChoices.add(choice);
                bestScore = score;
            } else if (score == bestScore) {
                bestChoices.add(choice);
            }
        }

        return chooseRandomChoice(bestChoices);
    }

    /**
     * Returns the highest-priority target cards based on score.
     *
     * @param gameState  the current game state
     * @param gameRules  the game rules for scoring
     * @param nobleFocus whether to prioritize noble-related bonuses
     * @param limit      the maximum number of targets to return
     * @return a list of priority CardChoices
     */
    public List<CardChoice> getPriorityTargets(GameState gameState, GameRules gameRules, boolean nobleFocus, int limit) {
        List<CardChoice> remaining = new ArrayList<>(getAllChoices(gameState));
        List<CardChoice> targets = new ArrayList<>();

        while (targets.size() < limit && remaining.size() > 0) {
            CardChoice best = remaining.get(0);
            for (CardChoice choice: remaining) {
                if (getCardScore(choice, gameState, gameRules, nobleFocus) > getCardScore(best, gameState, gameRules, nobleFocus)) {
                    best = choice;
                }
            }
            targets.add(best);
            remaining.remove(best);
        }
        return targets;
    }

    /**
     * Calculates a heuristic score for a card choice.
     *
     * @param choice     the card choice to score
     * @param gameState  the current game state
     * @param gameRules  the game rules for cost/noble calculations
     * @param nobleFocus whether to prioritize noble-related bonuses
     * @return the heuristic score (higher is better)
     */
    public int getCardScore(CardChoice choice, GameState gameState, GameRules gameRules, boolean nobleFocus) {
        DevelopmentCard card = choice.getCard();
        int score = card.getPoints() * 4;
        score += getDiscountUsefulness(card, gameState, nobleFocus);
        score += getNobleUsefulness(card, gameState, nobleFocus);
        score -= getMissingGems(gameRules, card) * 2;
        score -= getWasteCount(gameRules, card);
        score -= getTierPenalty(card, gameState, gameRules);
        score += getDenyBonus(choice, gameState, gameRules);

        if (choice.isReserved()) {
            score += 3;
        }
        if (!nobleFocus) {
            score += card.getPoints() * 2;
        }
        if (isEarlyGame(gameState) && card.getLevel() == 1 && card.getPoints() == 0) {
            score += 8;
        }
        return score;
    }

    /**
     * Calculates how useful a card's bonus is for purchasing future cards.
     *
     * @param card       the card to evaluate
     * @param gameState  the current game state
     * @param nobleFocus whether to prioritize noble-related bonuses
     * @return a usefulness score
     */
    public int getDiscountUsefulness(Card card, GameState gameState, boolean nobleFocus) {
        DevelopmentCard card2 = (DevelopmentCard) card;
        int usefulness = 0;
        Map<GemColor, Integer> bonuses = calculateBonuses();

        for (CardChoice choice: getVisibleChoices(gameState)) {
            Card other = choice.getCard();
            if (other.equals(card)) {
                continue;
            }
            if (other.getCost().getRequired(card2.getBonus()) > 0) {
                usefulness += other.getPoints() + 1;
            }
        }

        for (Card reserved: getReservedCards()) {
            DevelopmentCard reserved2 = (DevelopmentCard) reserved;
            if (reserved2.equals(card2)) {
                continue;
            }
            if (reserved.getCost().getRequired(card2.getBonus()) > 0) {
                usefulness += 2;
            }
        }

        if (bonuses.get(card2.getBonus()) < 3) {
            usefulness += (3 - bonuses.get(card2.getBonus())) * 2;
        }
        if (nobleFocus && getOpeningNobleColors(gameState).contains(card2.getBonus())) {
            usefulness += 4;
        }
        return usefulness;
    }

    /**
     * Calculates how useful a card is for progressing toward noble claims.
     *
     * @param card       the card to evaluate
     * @param gameState  the current game state
     * @param nobleFocus whether to prioritize noble-related bonuses
     * @return a usefulness score
     */
    public int getNobleUsefulness(Card card, GameState gameState, boolean nobleFocus) {
        DevelopmentCard card2 = (DevelopmentCard) card;
        int usefulness = 0;
        Map<GemColor, Integer> bonuses = calculateBonuses();

        for (Noble noble: gameState.getAvailableNobles()) {
            int required = noble.getRequirements().get(card2.getBonus());
            if (required <= bonuses.get(card2.getBonus())) {
                continue;
            }
            usefulness += noble.getPoints();
            if (nobleFocus) {
                usefulness += 6;
            } else {
                usefulness += 2;
            }
            if (countRemainingNobleColors(noble) == 1) {
                usefulness += 6;
            }
        }
        return usefulness;
    }

    /**
     * Calculates a penalty for buying expensive cards too early in the game.
     *
     * @param card      the card to evaluate
     * @param gameState the current game state
     * @param gameRules the game rules for cost calculation
     * @return the tier penalty (higher means worse)
     */
    public int getTierPenalty(Card card, GameState gameState, GameRules gameRules) {
        DevelopmentCard card2 = (DevelopmentCard) card;
        if (!isEarlyGame(gameState)) {
            return 0;
        }

        int missing = getMissingGems(gameRules, card2);
        if (card2.getLevel() == 3 && missing >= 4) {
            return 8 + missing;
        }
        if (card2.getLevel() == 2 && missing >= 3) {
            return 4 + missing;
        }
        if (card2.getLevel() == 1 && missing >= 4) {
            return 2;
        }
        return 0;
    }

    /**
     * Calculates a bonus for denying opponents access to a card.
     *
     * @param choice    the card choice to evaluate
     * @param gameState the current game state
     * @param gameRules the game rules for opponent affordability checks
     * @return the deny bonus (higher means more valuable to deny)
     */
    public int getDenyBonus(CardChoice choice, GameState gameState, GameRules gameRules) {
        if (choice.isReserved()) {
            return 0;
        }

        int deny = 0;
        for (Player player: gameState.getPlayers()) {
            if (player == this) {
                continue;
            }
            int threat = assessThreat(player, gameState, gameRules);
            int missing = gameRules.countMissingGems(player, choice.getCard());
            if (missing == 0) {
                deny += 6 + threat / 8;
            } else if (missing == 1) {
                deny += 4 + threat / 10;
            } else if (missing == 2) {
                deny += 2 + threat / 12;
            }
            if (choice.getCard().getPoints() > 0 && player.getPoints() >= gameState.getWinningThreshold() - 3) {
                deny += 3 + choice.getCard().getPoints() * 2;
            }
        }
        return deny;
    }

    /**
     * Assesses the threat level of an opponent based on their points and card proximity.
     *
     * @param player    the opponent to assess
     * @param gameState the current game state
     * @param gameRules the game rules for cost calculation
     * @return a threat score (higher means more dangerous)
     */
    public int assessThreat(Player player, GameState gameState, GameRules gameRules) {
        int threat = player.getPoints() * 3;
        if (player.getPoints() >= gameState.getWinningThreshold() - 3) {
            threat += 10;
        }

        int bestCard = 0;
        List<Card> cards = new ArrayList<>();
        for (CardChoice choice: getVisibleChoices(gameState)) {
            cards.add(choice.getCard());
        }
        cards.addAll(player.getReservedCards());

        for (Card card: cards) {
            int cardThreat = card.getPoints() * 3;
            int missing = gameRules.countMissingGems(player, card);
            if (missing == 0) {
                cardThreat += 8;
            } else if (missing == 1) {
                cardThreat += 5;
            } else if (missing == 2) {
                cardThreat += 3;
            }
            if (cardThreat > bestCard) {
                bestCard = cardThreat;
            }
        }

        threat += bestCard;
        threat += player.getReservedCards().size();
        return threat;
    }

    /**
     * Chooses a visible card to reserve based on score and deny value.
     *
     * @param gameState  the current game state
     * @param gameRules  the game rules for validation
     * @param nobleFocus whether to prioritize noble-related bonuses
     * @return the best CardChoice to reserve, or null if not worth reserving
     */
    public CardChoice getReserveChoice(GameState gameState, GameRules gameRules, boolean nobleFocus) {
        if (!gameRules.canReserveCard(this)) {
            return null;
        }

        List<CardChoice> visible = getVisibleChoices(gameState);
        if (visible.size() == 0) {
            return null;
        }

        CardChoice best = getBestChoice(visible, gameState, gameRules, nobleFocus);
        int score = getCardScore(best, gameState, gameRules, nobleFocus);
        int missing = getMissingGems(gameRules, best.getCard());
        int deny = getDenyBonus(best, gameState, gameRules);

        if (isEarlyGame(gameState) && getReservedCards().size() < 2) {
            if (score >= 12 || missing <= 1 || nobleFocus && getOpeningNobleColors(gameState).contains(best.getCard().getBonus())) {
                return best;
            }
        }
        if (deny >= 6) {
            return best;
        }
        if (best.getCard().getPoints() >= 3 && missing <= 4) {
            return best;
        }
        return null;
    }

    /**
     * Chooses a gem-taking move based on weighted priorities toward target cards.
     *
     * @param gameState  the current game state
     * @param gameRules  the game rules for validation
     * @param nobleFocus whether to prioritize noble-related bonuses
     * @return a description of the gem move taken, or empty string if none possible
     */
    public String chooseGemMove(GameState gameState, GameRules gameRules, boolean nobleFocus) {
        Map<GemColor, Integer> weights = new HashMap<>();
        List<CardChoice> targets = getPriorityTargets(gameState, gameRules, nobleFocus, 4);

        for (int i = 0; i < targets.size(); i++) {
            int base = 3;
            if (i == 0) {
                base = 8;
            } else if (i == 1) {
                base = 5;
            }

            CardChoice choice = targets.get(i);
            List<GemColor> needed = getNeededColorsForCard(gameRules, choice.getCard());
            for (GemColor color: needed) {
                Map<GemColor, Integer> cost = gameRules.getDiscountedCost(this, choice.getCard());
                int required = cost.get(color);
                int owned = getSpecificGem(color);
                if (required > owned) {
                    addWeight(weights, color, (required - owned) * base);
                } else {
                    addWeight(weights, color, base);
                }
            }
            if (choice.getCard() instanceof DevelopmentCard) {
                DevelopmentCard card = (DevelopmentCard) choice.getCard();
                addWeight(weights, card.getBonus(), base - 2);
            }
        }

        if (nobleFocus) {
            List<GemColor> nobleColors = getOpeningNobleColors(gameState);
            for (GemColor color: nobleColors) {
                addWeight(weights, color, 3);
            }
        }

        Map<GemColor, Integer> bonus = calculateBonuses();
        for (GemColor color: GemColor.values()) {
            if (color.equals(GemColor.GOLD_JOKER)) {
                continue;
            }
            if (bonus.get(color) >= 3) {
                addWeight(weights, color, -(bonus.get(color) - 2) * 2);
            }
            if (getSpecificGem(color) > 2) {
                addWeight(weights, color, -(getSpecificGem(color) - 2) * 2);
            }
        }

        String move = takeWeightedGemMove(gameState, gameRules, weights);
        if (move.endsWith("had no useful move.")) {
            return "";
        }
        return move;
    }

    /**
     * Returns the gem colors most demanded by available nobles.
     *
     * @param gameState the current game state
     * @return a list of the top 3 most-needed GemColors for nobles
     */
    public List<GemColor> getOpeningNobleColors(GameState gameState) {
        Map<GemColor, Integer> counts = new HashMap<>();
        for (GemColor color: GemColor.values()) {
            counts.put(color, 0);
        }

        for (Noble noble: gameState.getAvailableNobles()) {
            for (Map.Entry<GemColor, Integer> entry: noble.getRequirements().entrySet()) {
                counts.put(entry.getKey(), counts.get(entry.getKey()) + entry.getValue());
            }
        }

        List<GemColor> chosen = new ArrayList<>();
        while (chosen.size() < 3) {
            GemColor best = null;
            for (GemColor color: GemColor.values()) {
                if (color.equals(GemColor.GOLD_JOKER) || chosen.contains(color)) {
                    continue;
                }
                if (best == null || counts.get(color) > counts.get(best)) {
                    best = color;
                }
            }
            if (best == null) {
                break;
            }
            chosen.add(best);
        }
        return chosen;
    }

    /**
     * Decides which deck level to reserve a hidden card from.
     *
     * @param gameState  the current game state
     * @param nobleFocus whether to prioritize noble-related bonuses
     * @return the deck level (1-3), or 0 if all decks are empty
     */
    public int getHiddenReserveLevel(GameState gameState, boolean nobleFocus) {
        int preferred = nobleFocus ? 2 : 3;
        if (gameState.getCardMarket().getDeckSize(preferred) > 0) {
            return preferred;
        }
        if (gameState.getCardMarket().getDeckSize(2) > 0) {
            return 2;
        }
        if (gameState.getCardMarket().getDeckSize(1) > 0) {
            return 1;
        }
        if (gameState.getCardMarket().getDeckSize(3) > 0) {
            return 3;
        }
        return 0;
    }
}
